-- AlterTable
ALTER TABLE "User" ADD COLUMN     "lastPlanUpdateAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "planEndAt" TIMESTAMP(3),
ADD COLUMN     "planStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "submissionCount" INTEGER NOT NULL DEFAULT 0;
